### PR TITLE
Add optional scale parameter to flat_correct. Fixes issue #577

### PR DESCRIPTION
**Pull request by bjweiner**
Please have a look at the following list and replace the "[ ]" with a "[x]" if
the answer to this question is yes.

- [ ] For new contributors: Did you add yourself to the "Authors.rst" file?

For documentation changes:

- [ ] For documentation changes: Does your commit message include a "[skip ci]"?
      Note that it should not if you changed any examples!

For bugfixes:

- [ ] Did you add an entry to the "Changes.rst" file?
- [ ] Did you add a regression test?
- [ ] Does the commit message include a "Fixes #issue_number" (replace "issue_number").
- [ ] Does this PR add, rename, move or remove any existing functions or parameters?

For new functionality:

- [ ] Did you add an entry to the "Changes.rst" file?
- [x] Did you include a meaningful docstring with Parameters, Returns and Examples?
- [x] Does the commit message include a "Fixes #issue_number" (replace "issue_number").
- [ ] Did you include tests for the new functionality?
- [ ] Does this PR add, rename, move or remove any existing functions or parameters?

Please note that the last point is not a requirement. It is meant as a check if
the pull request potentially breaks backwards-compatibility.

-----------------------------------------

### CODE REVIEW

**Comment by mwcraig** [comment]
@bjweiner -- not sure if you intended this PR to be opened on the main astropy repo or not...it would be great to have the PR on the main repo! I can help with that if you need some help.

Thanks!

**Comment by bjweiner** [comment]
@mwcraig Thanks - I intended to open the pull request on the fork, and then open it on the main astropy repo, once I was sure I knew what I was doing.  I found the github documentation about how to initiate the pull request confusing. (and I'm at a conference so not on a full duty cycle.) Your suggestions for how to proceed are welcome.

The actual code is ready to be looked at, I think.

**Comment by mwcraig** [comment]
Not a problem! First, click on the code tab (in your fork) then the "Pull Request" link:

bjweiner_ccdproc__astropy_affiliated_package_for_reducing_optical_ir_ccd_data

Then, select the `bjweiner-patch-1` branch: 

comparing_astropy_master___bjweiner_master_ _astropy_ccdproc

That should give you a big green "Create pull request" button which will then open the PR in the right place....but if it doesn't or you are not sure if it did, please let me know!

**Comment by mwcraig** [comment]
@bjweiner -- do you object to me pulling this code into the official astropy/ccdproc repo?

**Comment by bjweiner** [comment]
Great! Thanks.

**Pull request merged**
